
const CAM_STATE = {
    UNKNOWN: "UNKNOWN",
    CONNECTING: "CONNECTING",
    CONNECTED: "CONNECTED",
    LIVEVIEWING: "LIVEVIEWING",
    CAPTURING: "CAPTURING",
    DISCONNECTED: "DISCONNECTED",
};

export default CAM_STATE;